### ISSUE TITLE
Bug: rules()  "required" is generated before "*_default"

### ISSUE THREAD

**Issue by siggi-k** [php-openapi/yii2-openapi#22]
The automatic generation of rules() first generates 'required' and then 'default' values.
Consequently, default values are not considered when checking 'required'.
The 'required' rules should therefore be generated after 'default'.

Example 

schema.yaml
```
...

      required:
        - verified
      properties:
         verified:
            type: boolean
            default: false
...
```

This means that "verified" must be set. If it is not passed in a form, it must be saved as false.

The succession of generic "rules".

ACTUAL STATE

```
'trim' => [...],
'required' => [...],
...
'verified_default' => [['verified'], 'default', 'value' => false],
...

```

TARGET STATE

```
'trim' => [...],
'verified_default' => [['verified'], 'default', 'value' => false],
// all defaults
'required' => [...],
...
```
